apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::211125364218:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-S9KO9PKoGDSv
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee 
      userarn: arn:aws:iam::211125364218:user/suresh
      username: suresh 
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-12T07:03:27Z"
  name: aws-auth
  namespace: kube-system
  uid: d6dd8e6f-6d07-46f3-b5a4-18a6511ddb39
